services:
  db: 
    image: postgres:16.3
    restart: always
    container_name: postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "${DB_PORT}:5432"
    env_file:
      - .env
    networks:
      - webserverauditorias_default

  pgadmin:
    image: dpage/pgadmin4:8.8
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: jearimmodesto@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - webserverauditorias_default

  web:
    build: .
    container_name: django
    # command: gunicorn server.wsgi:application --bind 0.0.0.0:8000
    # Changed to use sh for Nodemon compatibility
    # command: ["sh", "-c", "npm install -g nodemon && gunicorn server.wsgi:application --bind 0.0.0.0:8000"]
    # command: ["sh", "-c", "gunicorn server.wsgi:application --bind 0.0.0.0:8000"]    
    # command: ["sh", "-c", "nodemon --exec 'gunicorn server.wsgi:application --bind 0.0.0.0:8000'"]
    # command: ["/usr/local/bin/nodemon", "--exec", "gunicorn server.wsgi:application --bind 0.0.0.0:8000"]
    # command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    # command: ["/usr/local/bin/nodemon", "--watch", "/app", "--ext", "py,html", "--exec", "python manage.py runserver 0.0.0.0:8000"]
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - webserverauditorias_default

volumes:
  postgres_data:
  pgadmin_data:

networks:
  webserverauditorias_default:
    driver: bridge